name: Some-name
env:
    GITHUB_ACTOR: ${{ github.event.commits[0].author.name }}
on: [push]

jobs:
    Get-info-from-github:
        runs-on: ubuntu-latest

        steps:
            - name: Dump Github Context
              run : echo "$GITHUB_ACTOR"
