name: Some-name

on: [push]

jobs:
    Get-info-from-github:
        runs-on: ubuntu-latest

        steps:
            - name: Get Runner Context
              env :
                RUNNER_CONTEXT: ${{ toJson(runner) }}
              run : echo "$RUNNER_CONTEXT"  
