name: Some-name2

on: [push]

jobs:
    Get-info-from-github:
        runs-on: self-hosted

        steps:
            - name: Get Runner Context
              env :
                RUNNER_CONTEXT: ${{ toJson(runner) }}
              run : echo "$RUNNER_CONTEXT"  
