name: Build and push of Docker image

on:
    workflow_dispatch: 
        inputs:
          environment:
            description: "Value for tag"
            required: true
            default: "default-tag"

jobs:
    Get-info-from-github:
        runs-on: self-hosted

        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1

            - name: Build of docker image
              run : docker build -t terezabisharyan/some-image:some-tag .
              
            - name: Push image on Docker Hub
              run : |
                docker login -u terezabisharyan -p ${{ secrets.DOCKER_HUB_PSW }}
                docker push terezabisharyan/some-image:some-tag

            - name: Get Runner Context
              env :
                RUNNER_CONTEXT: ${{ toJson(runner) }}
              run : echo "$RUNNER_CONTEXT" 
              
            - name: Print input value
              run : echo "${{ github.event.inputs.environment }}"  
