name: Build and push of Docker image

on:
    workflow_dispatch: 
        inputs:
          tag_value:
            description: "Value for tag of image"
            required: true
            default: "default-tag"

env:
    TAG: ${{ github.event.inputs.tag_value }}          
    #VAL: ${{  }}

jobs:
    Get-info-from-github:
        runs-on: self-hosted

        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1

            - name: Build of docker image
              run : docker build -t terezabisharyan/some-image:$TAG .
              
            - name: Push image on Docker Hub
              run : |
                docker login -u terezabisharyan -p ${{ secrets.DOCKER_HUB_PSW }}
                docker push terezabisharyan/some-image:$TAG

            - name: Get Runner Context
              env :
                RUNNER_CONTEXT: ${{ toJson(runner) }}
              run : echo "$RUNNER_CONTEXT" 
            
            - name: Get data from Github Context
              run : echo " SHA is --- ${{ github.sha }}"